version: '3'

name: cobbleweb

volumes:
  sample-database-volume: {}

services:
  api:
    image: cobbleweb-api
    container_name: cobbleweb-api
    build:
      context: ./api/
      dockerfile: ./Dockerfile
    ports:
      - '${PORT}:${PORT}'
    environment:
      NODE_ENV: development
    command: npm run start:dev

  website:
    image: cobbleweb-website
    container_name: cobbleweb-website
    build:
      context: ./website/
      dockerfile: ./Dockerfile
    ports:
      - '${WEBSITE_PORT}:${WEBSITE_PORT}'
    environment:
      NODE_ENV: development
      REACT_APP_API_URL: http://localhost:${PORT}/api
    command: npm run start

  database:
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_DB_PASSWORD}
